name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: read
    concurrency:
      group: release-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Run uv build - main package
        uses: ./.github/actions/uv-build
        with:
          dist_dir: "./dist/rogue-ai"
      
      - name: Prepare Pypi release - main package
        uses: ./.github/actions/prepare-pypi
        with:
          dist_dir: "./dist/rogue-ai"
          package_name: "rogue-ai"

      - name: Publish to PyPI - main package
        uses: pypa/gh-action-pypi-publish@release/v1
        env:
          name: "pypi"
          url: "https://pypi.org/p/rogue-ai"
        with:
          packages-dir: "./dist/rogue-ai"

      - name: Run uv build - sdk package
        uses: ./.github/actions/uv-build
        with:
          workdir: "sdks/python"
          dist_dir: "./dist/rogue-ai-sdk"
          
      - name: Prepare Pypi release - sdk package
        uses: ./.github/actions/prepare-pypi
        with:
          dist_dir: "./dist/rogue-ai-sdk"
          package_name: "rogue-ai"
  
      - name: Publish to PyPI - sdk package
        uses: pypa/gh-action-pypi-publish@release/v1
        env:
          name: "pypi"
          url: "https://pypi.org/p/rogue-ai-sdk"
        with:
          packages-dir: "./dist/rogue-ai-sdk"

      - name: Build tui
        uses: ./.github/actions/tui-build
        with:
          build_all: "true"
          build_dir: "/opt/dist/rogue-tui"

      - name: Create release zip
        id: create_zip
        run: |
          cd /opt/dist
          zip -9r rogue-release-${{ github.ref_name }}.zip ./rogue-tui/* ./rogue-ai/* ./rogue-ai-sdk/*
          echo "zip_path=/opt/dist/rogue-release-${{ github.ref_name }}.zip" >> $GITHUB_OUTPUT

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rogue-release
          path: ${{ steps.create_zip.outputs.zip_path }}
          retention-days: 365  # TODO: how much time do we need to keep the release artifacts?

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.create_zip.outputs.zip_path }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
